alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /
name: do-db-config-ui
region: lon
static_sites:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: false
    repo: jkpe/do-db-config-ui
  name: web
  source_dir: /
  build_command: npm run build
