name: App Platform - Deployment

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
 deploy-app:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Deploy the app
       uses: digitalocean/app_action/deploy@v2.0.9
       with:
         token: ${{ secrets.DO_TOKEN }} 
         project_id: d3317450-0e85-40b3-907a-4c16edea7bf0